services:
  - type: web
    name: weeklypulse-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -e .
    startCommand: uvicorn src.weeklypulse.main_api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: GROQ_API_KEY
        sync: false
      - key: WEEKLYPULSE_DRAFT_TO
        sync: false
      - key: APP_NAME
        value: Groww
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
      - key: GOOGLE_TOKEN_JSON
        sync: false
    healthCheckPath: /
    autoDeploy: true
